#!/bin/sh


# display help
if [ ! -z $( echo "$@" | grep -e '-[a-zA-Z]*h') ]; then
	echo "will merge --no-ff given branch then push to origin and finally delete branch locally and from origin"
	echo "usage: git mpd feature-branch"
	exit
fi

branch="$@"
isLocal=1
if [ -z "$branch" ]; then
	echo "Please select a branch to merge first"
	exit
fi
if [ -z $(git branch |grep "$branch") ]; then
	isLocal=0
fi
git merge --no-ff "$branch" && git push origin && (([ $isLocal ] && git branch -d "$branch") || [ $isLocal -eq 0 ] ) && git push origin :$branch
